[package]
name = "consuming_crates"
version = "0.1.0"
edition = "2021"
authors = ["Omar Belghaouti <omarbelghaouti@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
